### ISSUE TITLE
Like and Comment numbers are not loaded to card component on WebApp

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#481] opened 2023-12-24 21:50 UTC
Card component is not showing correct like and comment numbers. We need to check new enhancement's functionality.

**Comment by gorkemkuyucu** [comment] 2023-12-24 21:55
I noticed that it is giving right numbers under myStories component. I think backend response is different for other pages. @hdenizdogan can you confirm that?

**Comment by gokalpayaz** [comment] 2023-12-27 20:02
@gorkemkuyucu , i fixed the issue with the likes but comment issue still persists due to insufficient response from server.
@hdenizdogan could you add commentSize (like you do with likeSize) to the responses where we request stories?

Then we can close the issue with a pr

**Comment by hdenizdogan** [comment] 2023-12-27 20:26
@gokalpayaz do you need commentLikeSize or CommentSize?

**Comment by hdenizdogan** [comment] 2023-12-27 20:49
@gokalpayaz development branch now includes likeSize for comment. Please confirm and close the issue if expectation is met.

**Comment by gokalpayaz** [comment] 2023-12-27 21:11
> @gokalpayaz development branch now includes likeSize for comment. Please confirm and close the issue if expectation is met.

@hdenizdogan, i think there is a missunderstanding. we already have likeSize. What we need is commentSize

**Comment by hdenizdogan** [comment] 2023-12-27 21:22
My mistake. please check again with the latest commit.

**Comment by gokalpayaz** [comment] 2023-12-29 21:20
i can confirm that it works. opening a pr

**Closed** 2023-12-30 07:13 UTC
Labels: bug, frontend, commit needed, react, webApp
